models: 
  - name: stg_olist_customers
    columns:
      - name: customer_id
        description: Primary key for this table
        data_tests:
          - unique
          - not_null
      - name: customer_unique_id
        data_tests:
          - not_null

  - name: stg_olist_orders
    columns:
      - name: order_id
        description: Primary key for this table
        data_tests:
          - unique 
          - not_null
      - name: customer_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_olist_customers')
                field: customer_id

  - name: stg_olist_order_items
    columns:
      - name: order_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_olist_orders')
                field: order_id
      - name: order_item_id
        data_tests:
          - not_null
      - name: product_id
        data_tests:
          - not_null
      - name: seller_id
        data_tests:
          - not_null

  - name: stg_olist_products
    columns:
      - name: product_id
        data_tests:
          - unique 
          - not_null

  - name: stg_olist_sellers
    columns:
      - name: seller_id
        data_tests:
          - unique 
          - not_null

  - name: stg_olist_order_payments
    columns:
      - name: order_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_olist_orders')
                field: order_id
      - name: payment_sequential
        data_tests:
          - not_null

  - name: stg_olist_order_reviews
    columns:
      - name: review_id
        data_tests:
          - not_null
      - name: order_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_olist_orders')
                field: order_id
      - name: review_score
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 1
                max_value: 5

